# 信息配置

## 标题
title: OninesixY的小站

## 标语
tagline: TheOninesixY.github.io | OninesixY.pages.dev

## 描述
description: 一个我都不知道有什么用的网站

## 图标
favicon: /favicon.png

# ----------分割线----------

# 样式配置

## 主题
remote_theme: "mmistakes/so-simple-theme"

## 皮肤
skin: "/assets/css/skins/light.css"
