#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "🚚 打包并提交中..."

# 执行打包命令
vitepress build

if [ $? -ne 0 ]; then
    echo "❌ 打包失败！已自动拦截提交"
    exit 1 # 显式返回错误码，强制中断 Git 提交程序
fi

echo "✔️ 打包成功，已放入暂存区"
git add .

# 获取当前 Git 临时 Commit 信息文件的路径
COMMIT_MSG_FILE=$1

if [ -n "$COMMIT_MSG_FILE" ] && [ -f "$COMMIT_MSG_FILE" ]; then
    # 读取原本的 commit 信息
    ORIGINAL_MSG=$(cat "$COMMIT_MSG_FILE")
    
    # 在原本的信息最前面，自动加上 [build] 暗号
    echo "[build] $ORIGINAL_MSG" > "$COMMIT_MSG_FILE"
    echo "🔒 已在提交信息开头注入已构建暗号"
fi