name: VitePress Dual Deploy

on:
  push:
    branches:
      - main

# 设置权限
permissions:
  contents: read
  pages: write
  id-token: write

# 确保同一时间只有一个部署任务在运行，避免版本冲突
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  local-deploy:
    # 如果提交信息里包含[build]，该更新已经在本地编译完成，无需云端Build
    if: contains(github.event.head_commit.message, '[build]')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # 电脑已经编译好了，直接上传根目录的 docs 文件夹给 Pages
          path: docs

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

  cloud-deploy:
    # 如果提交信息里不包含[build]将用云端 Build
    if: "!contains(github.event.head_commit.message, '[build]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Site
        # 云端把新产物生成到 docs 目录
        run: npx vitepress build

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # 上传在云端生成的 docs 文件夹
          path: docs

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4